litrus/modules/accounts/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views

from litrus.modules.accounts.views import *


urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout, { 'next_page': '/' }, name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^email/validation/$', EmailValidationView.as_view(), name='email-validation'),
    url(r'^password/reset/$', PasswordResetView.as_view(), name='password-reset'),
    url(r'^subscription/$', SubscriptionView.as_view(), name='subscription'),
    url(r'^subscription/billing/$', SubscriptionBillingView.as_view(), name='subscription-billing'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^profile/edit/$', ProfileEditView.as_view(), name='profile-edit'),
    url(r'^settings/$', SettingsView.as_view(), name='settings'),
]

litrus/modules/courses/urls.py
from django.conf.urls import include, url

from litrus.modules.courses.views import *


urlpatterns = [
    url(r'^$', CoursesView.as_view(), name='courses'),
    url(r'^user/enrollment/$', CourseEnrollmentView.as_view(), name='course-enrollment'),
    url(r'^(?P<slug>[-\w]+)/$', CourseView.as_view(), name='course'),
    url(r'^(?P<slug>[-\w]+)/dashboard/$', CourseDashboardView.as_view(), name='course-dashboard'),
    url(r'^(?P<slug>[-\w]+)/lesson/(?P<lesson_id>[-\w]+)$', CourseLessonView.as_view(), name='course-lesson'),
    url(r'^user/finish/lesson/$', UserFinishLessonView.as_view(), name='user-finish-lesson'),
    url(r'^(?P<slug>[-\w]+)/discussion/$', CourseDiscussionView.as_view(), name='course-discussion'),
    url(r'^(?P<slug>[-\w]+)/discussion/question/(?P<question_id>[-\w]+)$', CourseDiscussionQuestionView.as_view(), name='course-discussion-question'),
    url(r'^(?P<slug>[-\w]+)/discussion/question/add/(?:/(?P<question_id>[-\w]+)/)?$', CourseDiscussionQuestionAddView.as_view(), name='course-discussion-question-add'),
    url(r'^(?P<slug>[-\w]+)/user/comment/question/(?P<question_id>[-\w]+)$', UserCommentQuestionView.as_view(), name='user-comment-question'),
    url(r'^(?P<slug>[-\w]+)/openclose/question/(?P<question_id>[-\w]+)$', OpenCloseQuestionView.as_view(), name='open-close-question'),
    url(r'^(?P<slug>[-\w]+)/delete/question/(?P<question_id>[-\w]+)$', DeleteQuestionView.as_view(), name='delete-question'),
    url(r'^(?P<slug>[-\w]+)/delete/comment/$', DeleteCommentView.as_view(), name='delete-comment'),
]

litrus/modules/pages/urls.py
from django.conf.urls import include, url

from litrus.modules.pages.views import *


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
]

litrus/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
	url(r'^accounts/', include('litrus.modules.accounts.urls', namespace='accounts')),
	url(r'^courses/', include('litrus.modules.courses.urls', namespace='courses')),
	url(r'^', include('litrus.modules.pages.urls', namespace='pages')),
	url(r'^payments/paypal/', include('paypal.standard.ipn.urls')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litrus/modules/accounts/forms.py
from re import match

from django import forms
from django.contrib.auth.models import User
from django.core.validators import validate_email, EmailValidator
from django.utils.translation import ugettext_lazy as _


class RegisterForm(forms.Form):

    username = forms.CharField(label=_('Username'))
    email = forms.EmailField(label=_('Email'), validators=[EmailValidator])
    password = forms.CharField(
        label=_('Password'), widget=forms.PasswordInput)
    password_again = forms.CharField(
        label=_('Password Again'), widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()

        cleaned_data['username'] = cleaned_data.get('username', '').lower()
        cleaned_data['email'] = cleaned_data.get('email', '').lower()
        cleaned_data['password'] = cleaned_data.get('password', '')
        cleaned_data['password_again'] = cleaned_data.get('password_again', '')


        # Username validation.
        if not (3 < len(cleaned_data['username']) < 20):
            raise forms.ValidationError(_('Username length may be between 3 and 20 characters.'))
        if not match(r'^[a-zA-Z]+$', cleaned_data['username']):
            raise forms.ValidationError(_('Username value may contain only letters and numbers.'))

        # Password validation.

        if not (cleaned_data['password'] == cleaned_data['password_again']):
            raise forms.ValidationError(_('Passwords must be equal.'))

        if not (len(cleaned_data['password']) >= 6):
            raise forms.ValidationError(_('Password must be 6 character length.'))

        # Ensure email is not already registered.
        try:
            User.objects.get(email=cleaned_data['email'])
            raise forms.ValidationError(_('The email is already registered.'))
        except User.DoesNotExist:
            pass

        # Ensure username is not already registered.
        try:
            User.objects.get(username=cleaned_data['username'])
            raise forms.ValidationError(_('The username is already registered.'))
        except User.DoesNotExist:
            pass


class ProfileEditForm(forms.Form):

    first_name = forms.CharField(
        label=_('First Name'), required=False)
    last_name = forms.CharField(
        label=_('Last Name'), required=False)

    def clean_first_name(self):
        data = self.cleaned_data['first_name']

        if data == '':
            return data
        if not match(r'^[a-zA-Z\s]{2,50}$', data):
            raise forms.ValidationError(_('First name may contain only letters.'))

        return data

    def clean_last_name(self):
        data = self.cleaned_data['last_name']

        if data == '':
            return data
        if not match(r'^[a-zA-Z\s]{2,50}$', data):
            raise forms.ValidationError(_('Last name may contain only letters.'))

        return data

litrus/modules/accounts/views.py
from base64 import b16encode
from urllib import quote

from django.conf import settings
from django.contrib.auth import authenticate, login, REDIRECT_FIELD_NAME
from django.contrib.auth.models import User
from django.core.mail import EmailMessage, send_mail
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView, TemplateView, View
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from paypal.standard.forms import PayPalPaymentsForm

from litrus.models import *
from litrus.modules.accounts.decorators import *
from litrus.modules.accounts.forms import *
from litrus.utils import random_hash


class LoginView(View):
    template_name = 'accounts/login.html'

    def dispatch(self, request, *args, **kwargs):
        # Grab `next` value.
        kwargs[REDIRECT_FIELD_NAME] = request.POST.get(REDIRECT_FIELD_NAME,
            request.GET.get(REDIRECT_FIELD_NAME, ''))

        return super(self.__class__,
                     self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, kwargs)

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username_or_email', '')
        try:
            user = User.objects.get(email=username)
            username = user.username
        except User.DoesNotExist:
            pass
        user = authenticate(username=username,
                            password=request.POST.get('password', ''))
        if user is not None:
            login(request, user)
            return redirect(kwargs[REDIRECT_FIELD_NAME] or 'accounts:profile')
        else:
            kwargs['error'] = _('Username and password did not match. Please try again.')

        return render(request, self.template_name, kwargs)


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'

    def form_valid(self, form):
        user = User(username=form.cleaned_data['username'].lower(),
                    email = form.cleaned_data['email'].lower())
        user.set_password(form.cleaned_data['password'])
        user.is_active = False
        user.save()

        # Generate the token.
        token, created = EmailValidationToken.objects.get_or_create(user=user)
        token.token = random_hash()
        token.save()

        # Create the email body.
        activation_link = settings.SITE_URL + token.get_absolute_url()
        html_content = render_to_string('accounts/emails/register.html',
            { 'activation_link': activation_link })

        # Send email to the user.
        msg = EmailMessage(_('Activate your account'), html_content, 'from@example.com', [user.email])
        msg.content_subtype = 'html'
        msg.send()

        redirect_url = reverse('accounts:email-validation') + '?email=' + quote(user.email)
        return redirect(redirect_url)


class EmailValidationView(View):
    template_send = 'accounts/email_validation_send.html'
    template_sent = 'accounts/email_validation_sent.html'

    def dispatch(self, request, *args, **kwargs):
        kwargs['token'] = request.GET.get('token')
        kwargs['email'] = request.GET.get('email')
        return super(self.__class__,
                     self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        if kwargs['token']:
            # Grab token and validate account.
            try:
                token = PasswordResetToken.objects.get(token=kwargs['token'])
                token.user.is_active = True
                token.user.save()
            except PasswordResetToken.DoesNotExist:
                pass

            return redirect('accounts:login')
        if kwargs['email']:
            return render(request, self.template_sent, kwargs)

        return render(request, self.template_send, kwargs)


class PasswordResetView(View):
    template_email = 'accounts/password_reset_email.html'
    template_form = 'accounts/password_reset_form.html'
    template_sent = 'accounts/password_reset_sent.html'

    def dispatch(self, request, *args, **kwargs):
        kwargs['token'] = request.POST.get('token',
            request.GET.get('token', ''))
        kwargs['email'] = request.GET.get('email')
        return super(self.__class__,
                     self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        if kwargs['token']:
            return render(request, self.template_form, kwargs)
        if kwargs['email']:
            return render(request, self.template_sent, kwargs)

        return render(request, self.template_email, kwargs)

    def post(self, request, *args, **kwargs):
        if kwargs['token']:
            try:
                token = PasswordResetToken.objects.get(token=kwargs['token'])
            except PasswordResetToken.DoesNotExist:
                kwargs['error'] = _('Your token for reseting password is invalid.')
                return render(request, self.template_form, kwargs)

            password = request.POST.get('password', '')
            password_again = request.POST.get('password_again', '')

            if len(password) < 6:
                kwargs['error'] = _('Your password is too short.')
                return render(request, self.template_form, kwargs)

            if not(password == password_again):
                kwargs['error'] = _('Your passwords mismatch.')
                return render(request, self.template_form, kwargs)

            token.user.set_password(password)
            token.user.save()
            token.delete()

            return redirect('accounts:login')
        else:
            email = request.POST.get('email', '')
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                kwargs['error'] = _('The email is invalid.')
                return render(request, self.template_email, kwargs)

            # Generate the token.
            token, created = PasswordResetToken.objects.get_or_create(user=user)
            token.token = random_hash()
            token.save()

            reset_url = reverse('accounts:password-reset') + '?token=' + token.token

            send_mail(_('Password Reset'), reset_url, 'from@example.com',
                [email], fail_silently=False)

            redirect_url = reverse('accounts:password-reset') + '?email=' + quote(email)
            return redirect(redirect_url)


class SubscriptionView(TemplateView):
    template_name = 'accounts/subscription.html'

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(self.__class__, self).dispatch(
            request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        try:
            context['subscription'] = Subscription.objects.get(
                user=self.request.user)
        except Subscription.DoesNotExist:
            context['subscription'] = None

        return context


class SubscriptionBillingView(TemplateView):
    template_name = 'accounts/subscription_billing.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(self.__class__, self).dispatch(
            request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context['plans'] = SubscriptionPlan.objects.order_by('level')

        for plan in context['plans']:
            paypal_dict = {
                'invoice': random_hash(),
                'business': settings.PAYPAL_RECEIVER_EMAIL,
                'amount': plan.price,
                'item_number': plan.id,
                'item_name': plan.name,
                'custom': b16encode(self.request.user.email),
                'notify_url': settings.SITE_URL + reverse('paypal-ipn'),
                'return_url': settings.SITE_URL + reverse('accounts:subscription'),
                'cancel_return': settings.SITE_URL + reverse('accounts:subscription-billing'),
            }
            plan.form = PayPalPaymentsForm(initial=paypal_dict)

        return context


class ProfileView(TemplateView):
    template_name = 'accounts/profile.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(self.__class__, self).dispatch(
            request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context['courses'] = Course.of_user(self.request.user)

        for course in context['courses']:
            course.date_enrolled = \
                CourseEnrollment.objects.get(
                    user=self.request.user, course=course).date_enrolled
            course.completed = \
                course.percentage_completed_of_user(self.request.user)[2]

        context['questions'] = DiscussionQuestion.objects.filter(
            user=self.request.user).order_by('-date_created')[:10]

        return context


class ProfileEditView(FormView):
    form_class = ProfileEditForm
    template_name = 'accounts/profile_edit.html'

    def get_initial(self):
        initial = super(self.__class__, self).get_initial()

        initial['first_name'] = self.request.user.first_name
        initial['last_name'] = self.request.user.last_name

        return initial

    def form_valid(self, form):
        user = self.request.user

        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']

        user.save()

litrus/modules/pages/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'pages/home.html'

litrus/templates/courses/course.html
{% extends "base.html" %}
{% load i18n %}
{% load litrustags %}

{% block content %}
    
    <div class="ui stackable page grid">
        <div class="row">
            <div class="six wide column">
                <h1 id="course-header">{{ course.name }}</h1>
                {% if not user_enrolled %}
                <form method="POST" action="{% url 'courses:course-enrollment' %}">
                    {% csrf_token %}
                    <input type="hidden" name="course_id" value="{{ course.id }}">
                    <button class="ui green large labeled icon fluid ui button"><i class="student icon"></i> {% trans 'Take This Course Now' %}</button>
                </form>
                {% else %}
                <a href="{% url 'courses:course-dashboard' course.slug %}" class="ui blue large labeled icon fluid ui button">
                    <i class="share icon"></i>
                    {% trans 'Go To Course Dashboard' %}
                </a>
                {% endif %}
            </div>
            <div class="ten wide column">
                {% if course.video %}
                <div class="video">
                    <video id="video" controls>
                        <source src="{{ course.video.url }}" type='video/mp4'>
                    </video>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="twelve wide column">
                <div class="ui segment">
                    {{ course.description | markdownify | safe }}
                    <div class="ui divider"></div>
                    <div class="ui stackable two column grid">
                        <div class="column">
                            <div class="ui huge header">{% trans 'Requirements' %}</div>
                            <ul class="ui bulleted list">
                            {% for requirement in course.requirements.splitlines %}
                                <li class="item">{{ requirement }}</a>
                            {% endfor %}
                            </ul>
                        </div>
                        <div class="column">
                            <div class="ui huge header">{% trans 'Target Audience' %}</div>
                            <ul class="ui bulleted list">
                            {% for target in course.target.splitlines %}
                                <li class="item">{{ target }}</a>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="ui huge header">{% trans 'Curriculum' %}</div>
                {% include "courses/partials/course_curriculum.html" %}
            </div>
            <div class="four wide column">
                <div class="ui massive vertical list">
                    <div class="item">
                        <i class="ui bookmark icon"></i>
                        <div class="content aligned">{{ course.category.name }}</div>
                    </div>
                    <div class="item">
                        <i class="ui comment icon"></i>
                        <div class="content aligned">{{ course.verbose_language }}</div>
                    </div>
                    <div class="item">
                        <i class="ui signal icon"></i>
                        <div class="content aligned">{{ course.verbose_level }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

litrus/templates/courses/course_dashboard.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
    
    <div class="ui stackable page grid">
        <div class="fifteen wide centered column">
            <h1 class="ui header">
                <img src="{% if course.logo %}{{ course.logo.url }}{% else %}{% static 'img/no-image.gif' %}{% endif %}" class="ui circular image">
                {{ course.name }}
            </h1>
            <div class="ui hidden divider"></div>
            <div class="ui pointing menu">
                <a href="{% url 'courses:course-dashboard' course.slug %}" class="item">{% trans 'Curriculum' %}</a>
                <a href="{% url 'courses:course-discussion' course.slug %}" class="item">{% trans 'Discussion' %}</a>
            </div>
            <div class="ui segment">
            {% block subcontent %}
                <div class="ui doubling two column grid">
                    <div class="ten wide column">
                        <div class="ui green progress active" data-percent="{{ completed }}" style="margin-bottom:0">
                            <div class="bar" style="transition-duration: 300ms; width: {{ completed }}%;">
                                <div class="progress">{{ completed }} %</div>
                            </div>
                        </div>
                        {% include "courses/partials/course_curriculum.html" %}
                    </div>
                    <div class="six wide column">
                        {% if next_lesson_url %}
                        <a href="{{ next_lesson_url }}" class="ui right labeled blue fluid icon button"><i class="right arrow icon"></i>Next Lesson</a>
                        {% endif %}
                    </div>
                </div>
            {% endblock %}
            </div>
        </div>
    </div>

{% endblock %}

litrus/templates/courses/course_discussion.html
{% extends "courses/course_dashboard.html" %}
{% load i18n %}
{% load staticfiles %}
{% load litrustags %}

{% block subcontent %}

    <div class="ui doubling two column grid">
        <div class="ten wide column">
            <h3 class="ui dividing header">{% trans 'Questions' %}</h3>
            <div class="ui large list">
                {% for question in questions %}
                <div class="item">
                    <img class="ui avatar image" data-content="{{ question.user.username }}" data-position="left center" data-variation="inverted" src="{% gravatar question.user.email %}">
                    <div class="content">
                        <a href="{% url 'courses:course-discussion-question' course.slug question.id %}" class="header">{{ question.title }}</a>
                        <div class="description" style="color:#ccc;font-size:15px">{% if not question.is_open %} <div class="ui purple mini label">CLOSED</div> {% endif %}{{ question.date_created | date:'d M' }}. {% if question.lesson %}<b>{{ question.lesson.section.number }}.{{ question.lesson.number }} {{ question.lesson.name | truncatechars:20 }}</b>{% endif %}</div>
                    </div>
                </div>
                {% empty %}
                <div class="ui small info message">
                    <p>{% trans 'No questions to show. Be the first!' %}</p>
                </div>
                {% endfor %}
            </div>
            <div class="ui hidden divider"></div>
            <div class="ui tiny buttons">
                <a{% if questions.has_previous %} href="{% url 'courses:course-discussion' course.slug %}?page={{ questions.previous_page_number }}"{% endif %} class="ui labeled icon{% if not questions.has_previous %} disabled{% endif %} button"><i class="left chevron icon"></i> {% trans 'Back' %}</a>
                <a{% if questions.has_next %} href="{% url 'courses:course-discussion' course.slug %}?page={{ questions.next_page_number }}"{% endif %} class="ui right labeled icon{% if not questions.has_next %} disabled{% endif %} button">{% trans 'Forward' %} <i class="right chevron icon"></i></a>
            </div>
            <h3 class="ui dividing header">{% trans 'Recent Comments' %}</h3>
            <div class="ui small list">
                {% for comment in recent_comments %}
                <div class="item">
                    <img class="ui avatar image" src="{% gravatar comment.user.email %}">
                    <div class="content">
                    <a class="header">{{ comment.user.username }}</a>
                    <div class="description">On question <a href="{% url 'courses:course-discussion-question' course.slug comment.question.id %}"><b>{{ comment.question.title | truncatechars:20 }}</b></a> about {{ comment.date_created | timesince }} ago.</div>
                    </div>
                </div>
                {% empty %}
                <div class="ui small info message">
                    <p>{% trans 'No comments to show.' %}</p>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="six wide column">
            <a href="{% url 'courses:course-discussion-question-add' course.slug %}" class="ui labeled green fluid icon large button"><i class="pencil icon"></i> {% trans 'Write Question' %}</a>
            <div class="ui basic floated segment">
                <div class="ui statistics">
                    <div class="statistic">
                        <div class="label">{% trans 'Students' %}</div>
                        <div class="value">{{ users_enrolled_count }}</div>
                    </div>
                    <div class="statistic">
                        <div class="label">{% trans 'Questions' %}</div>
                        <div class="value">{{ questions_count }}</div>
                    </div>
                    <div class="statistic">
                        <div class="label">{% trans 'Closed' %}</div>
                        <div class="value">{{ questions_closed_count }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block script %}
    <script type="text/javascript">
        $(function() {
            $('img').popup();
        });
    </script>
{% endblock %}

litrus/templates/courses/course_discussion_question.html
{% extends "courses/course_dashboard.html" %}
{% load i18n %}
{% load litrustags %}

{% block subcontent %}

    <h2 class="ui header">
        <img src="{% gravatar question.user.email %}" class="ui circular image">
        <div class="content">
            {{ question.title }}
            <div class="sub header">
                {% trans 'By' %} {{ question.user.username }}. {{ question.date_created | date:'d M \a\t H A' }}. 
                {% if question.lesson %}<a href="{{ question.lesson.get_absolute_url }}" class="ui label">{{ question.lesson.section.number }}.{{ question.lesson.number }} {{ question.lesson.name | truncatechars:20 }}</a>{% endif %}
                {% if not question.is_open %} <div class="ui purple label">CLOSED</div>{% endif %}
            </div>
        </div>
        
    </h2>
    <div class="ui form">
        <div class="inline fields">
            {% if user_owns_question or request.user.is_superuser %}
            <form method="post" action="{% url 'courses:open-close-question' course.slug question.id %}">
                {% csrf_token %}
                <button class="ui purple basic compact button">
                    {% if question.is_open %}<i class="ban icon"></i> Close{% else %}<i class="pin icon"></i> Open{% endif %}
                </button>
            </form>
            <button id="delete-question-button" class="ui red basic compact button">
                <i class="trash icon"></i> Delete
            </button>
            {% endif %}
        </div>
    </div>
    <div class="ui divider"></div>
    <p>{{ question.content }}</p>

    <div class="ui comments">
      <h3 class="ui dividing header">{% trans 'Comments' %} ({{ comments | length }})</h3>
      {% for comment in comments %}
      <div class="comment">
        <a class="avatar">
          <img src="{% gravatar comment.user.email %}">
        </a>
        <div class="content">
          <a class="author">{{ comment.user.username }}</a>
          <div class="metadata">
            <span class="date">{{ comment.date_created | timesince }}</span>
          </div>
          <div class="text">
            {{ comment.content | markdownify | safe }}
          </div>
          {% if user_owns_question or request.user.is_superuser %}
          <div class="actions">
            <a href="#{{ comment.id }}" class="delete"><i class="trash icon"></i>Delete</a>
          </div>
          {% endif %}
        </div>
      </div>
      {% empty %}
      <div class="ui small info message">
          <p>{% trans 'No comments to show. Be the first!' %}</p>
      </div>
      {% endfor %}

        <form method="post" class="ui reply form" action="{% url 'courses:user-comment-question' course.slug question.id %}">
            {% csrf_token %}
            <div class="field">
                <textarea name="content"></textarea>
            </div>
            <button class="ui blue labeled submit icon button">
                <i class="icon edit"></i> {% trans 'Write Comment' %}
            </button>
        </form>

    </div>

    <div id="delete-question-modal" class="ui small modal">
        <i class="close icon"></i>
        <div class="header">
            {% trans 'Delete Question' %}
        </div>
        <div class="content">
            <div class="description">
                {% trans 'Are you sure you want to delete the question' %} "{{ question.title }}"?
            </div>
        </div>
        <div class="actions">
            <form method="post" action="{% url 'courses:delete-question' course.slug question.id %}">
                {% csrf_token %}
                <button class="ui red button">{% trans 'Yes! Delete it.' %}</button>
            </form>
        </div>
    </div>

    <div id="delete-comment-modal" class="ui small modal">
        <i class="close icon"></i>
        <div class="header">
            {% trans 'Delete Comment' %}
        </div>
        <div class="content">
            <div class="description">
                {% trans 'Are you sure you want to delete this comment?' %}
            </div>
        </div>
        <div class="actions">
            <form method="post" action="{% url 'courses:delete-comment' course.slug %}">
                {% csrf_token %}
                <input type="hidden" name="comment_id" value="">
                <button class="ui red button">{% trans 'Yes! Delete it.' %}</button>
            </form>
        </div>
    </div>

{% endblock %}

{% block script %}
    <script type="text/javascript">
        $(function() {
            $("#delete-question-button").click(function(event) {
                $('#delete-question-modal').modal('show');
            });

            $(".delete").click(function(event) {
                event.preventDefault();
                $("input[name=comment_id]").val($(this).attr('href').replace('#', ''));
                $('#delete-comment-modal').modal('show');
            });
        });
    </script>
{% endblock %}