litrus/modules/accounts/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views

from litrus.modules.accounts.views import *


urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout, { 'next_page': '/' }, name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^email/validation/$', EmailValidationView.as_view(), name='email-validation'),
    url(r'^password/reset/$', PasswordResetView.as_view(), name='password-reset'),
    url(r'^subscription/$', SubscriptionView.as_view(), name='subscription'),
    url(r'^subscription/billing/$', SubscriptionBillingView.as_view(), name='subscription-billing'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^profile/edit/$', ProfileEditView.as_view(), name='profile-edit'),
    url(r'^settings/$', SettingsView.as_view(), name='settings'),
]

litrus/modules/courses/urls.py
from django.conf.urls import include, url

from litrus.modules.courses.views import *


urlpatterns = [
    url(r'^$', CoursesView.as_view(), name='courses'),
    url(r'^user/enrollment/$', CourseEnrollmentView.as_view(), name='course-enrollment'),
    url(r'^(?P<slug>[-\w]+)/$', CourseView.as_view(), name='course'),
    url(r'^(?P<slug>[-\w]+)/dashboard/$', CourseDashboardView.as_view(), name='course-dashboard'),
    url(r'^(?P<slug>[-\w]+)/lesson/(?P<lesson_id>[-\w]+)$', CourseLessonView.as_view(), name='course-lesson'),
    url(r'^user/finish/lesson/$', UserFinishLessonView.as_view(), name='user-finish-lesson'),
    url(r'^(?P<slug>[-\w]+)/discussion/$', CourseDiscussionView.as_view(), name='course-discussion'),
    url(r'^(?P<slug>[-\w]+)/discussion/question/(?P<question_id>[-\w]+)$', CourseDiscussionQuestionView.as_view(), name='course-discussion-question'),
    url(r'^(?P<slug>[-\w]+)/discussion/question/add/(?:/(?P<question_id>[-\w]+)/)?$', CourseDiscussionQuestionAddView.as_view(), name='course-discussion-question-add'),
    url(r'^(?P<slug>[-\w]+)/user/comment/question/(?P<question_id>[-\w]+)$', UserCommentQuestionView.as_view(), name='user-comment-question'),
    url(r'^(?P<slug>[-\w]+)/openclose/question/(?P<question_id>[-\w]+)$', OpenCloseQuestionView.as_view(), name='open-close-question'),
    url(r'^(?P<slug>[-\w]+)/delete/question/(?P<question_id>[-\w]+)$', DeleteQuestionView.as_view(), name='delete-question'),
    url(r'^(?P<slug>[-\w]+)/delete/comment/$', DeleteCommentView.as_view(), name='delete-comment'),
]

litrus/modules/pages/urls.py
from django.conf.urls import include, url

from litrus.modules.pages.views import *


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
]

litrus/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
	url(r'^accounts/', include('litrus.modules.accounts.urls', namespace='accounts')),
	url(r'^courses/', include('litrus.modules.courses.urls', namespace='courses')),
	url(r'^', include('litrus.modules.pages.urls', namespace='pages')),
	url(r'^payments/paypal/', include('paypal.standard.ipn.urls')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litrus/modules/accounts/forms.py
from re import match

from django import forms
from django.contrib.auth.models import User
from django.core.validators import validate_email, EmailValidator
from django.utils.translation import ugettext_lazy as _


class RegisterForm(forms.Form):

    username = forms.CharField(label=_('Username'))
    email = forms.EmailField(label=_('Email'), validators=[EmailValidator])
    password = forms.CharField(
        label=_('Password'), widget=forms.PasswordInput)
    password_again = forms.CharField(
        label=_('Password Again'), widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()

        cleaned_data['username'] = cleaned_data.get('username', '').lower()
        cleaned_data['email'] = cleaned_data.get('email', '').lower()
        cleaned_data['password'] = cleaned_data.get('password', '')
        cleaned_data['password_again'] = cleaned_data.get('password_again', '')


        # Username validation.
        if not (3 < len(cleaned_data['username']) < 20):
            raise forms.ValidationError(_('Username length may be between 3 and 20 characters.'))
        if not match(r'^[a-zA-Z]+$', cleaned_data['username']):
            raise forms.ValidationError(_('Username value may contain only letters and numbers.'))

        # Password validation.

        if not (cleaned_data['password'] == cleaned_data['password_again']):
            raise forms.ValidationError(_('Passwords must be equal.'))

        if not (len(cleaned_data['password']) >= 6):
            raise forms.ValidationError(_('Password must be 6 character length.'))

        # Ensure email is not already registered.
        try:
            User.objects.get(email=cleaned_data['email'])
            raise forms.ValidationError(_('The email is already registered.'))
        except User.DoesNotExist:
            pass

        # Ensure username is not already registered.
        try:
            User.objects.get(username=cleaned_data['username'])
            raise forms.ValidationError(_('The username is already registered.'))
        except User.DoesNotExist:
            pass


class ProfileEditForm(forms.Form):

    first_name = forms.CharField(
        label=_('First Name'), required=False)
    last_name = forms.CharField(
        label=_('Last Name'), required=False)

    def clean_first_name(self):
        data = self.cleaned_data['first_name']

        if data == '':
            return data
        if not match(r'^[a-zA-Z\s]{2,50}$', data):
            raise forms.ValidationError(_('First name may contain only letters.'))

        return data

    def clean_last_name(self):
        data = self.cleaned_data['last_name']

        if data == '':
            return data
        if not match(r'^[a-zA-Z\s]{2,50}$', data):
            raise forms.ValidationError(_('Last name may contain only letters.'))

        return data

litrus/modules/accounts/views.py
from base64 import b16encode
from urllib import quote

from django.conf import settings
from django.contrib.auth import authenticate, login, REDIRECT_FIELD_NAME
from django.contrib.auth.models import User
from django.core.mail import EmailMessage, send_mail
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView, TemplateView, View
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from paypal.standard.forms import PayPalPaymentsForm

from litrus.models import *
from litrus.modules.accounts.decorators import *
from litrus.modules.accounts.forms import *
from litrus.utils import random_hash


class LoginView(View):
    template_name = 'accounts/login.html'

    def dispatch(self, request, *args, **kwargs):
        # Grab `next` value.
        kwargs[REDIRECT_FIELD_NAME] = request.POST.get(REDIRECT_FIELD_NAME,
            request.GET.get(REDIRECT_FIELD_NAME, ''))

        return super(self.__class__,
                     self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, kwargs)

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username_or_email', '')
        try:
            user = User.objects.get(email=username)
            username = user.username
        except User.DoesNotExist:
            pass
        user = authenticate(username=username,
                            password=request.POST.get('password', ''))
        if user is not None:
            login(request, user)
            return redirect(kwargs[REDIRECT_FIELD_NAME] or 'accounts:profile')
        else:
            kwargs['error'] = _('Username and password did not match. Please try again.')

        return render(request, self.template_name, kwargs)


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'

    def form_valid(self, form):
        user = User(username=form.cleaned_data['username'].lower(),
                    email = form.cleaned_data['email'].lower())
        user.set_password(form.cleaned_data['password'])
        user.is_active = False
        user.save()

        # Generate the token.
        token, created = EmailValidationToken.objects.get_or_create(user=user)
        token.token = random_hash()
        token.save()

        # Create the email body.
        activation_link = settings.SITE_URL + token.get_absolute_url()
        html_content = render_to_string('accounts/emails/register.html',
            { 'activation_link': activation_link })

        # Send email to the user.
        msg = EmailMessage(_('Activate your account'), html_content, 'from@example.com', [user.email])
        msg.content_subtype = 'html'
        msg.send()

        redirect_url = reverse('accounts:email-validation') + '?email=' + quote(user.email)
        return redirect(redirect_url)


class EmailValidationView(View):
    template_send = 'accounts/email_validation_send.html'
    template_sent = 'accounts/email_validation_sent.html'

    def dispatch(self, request, *args, **kwargs):
        kwargs['token'] = request.GET.get('token')
        kwargs['email'] = request.GET.get('email')
        return super(self.__class__,
                     self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        if kwargs['token']:
            # Grab token and validate account.
            try:
                token = PasswordResetToken.objects.get(token=kwargs['token'])
                token.user.is_active = True
                token.user.save()
            except PasswordResetToken.DoesNotExist:
                pass

            return redirect('accounts:login')
        if kwargs['email']:
            return render(request, self.template_sent, kwargs)

        return render(request, self.template_send, kwargs)


class PasswordResetView(View):
    template_email = 'accounts/password_reset_email.html'
    template_form = 'accounts/password_reset_form.html'
    template_sent = 'accounts/password_reset_sent.html'

    def dispatch(self, request, *args, **kwargs):
        kwargs['token'] = request.POST.get('token',
            request.GET.get('token', ''))
        kwargs['email'] = request.GET.get('email')
        return super(self.__class__,
                     self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        if kwargs['token']:
            return render(request, self.template_form, kwargs)
        if kwargs['email']:
            return render(request, self.template_sent, kwargs)

        return render(request, self.template_email, kwargs)

    def post(self, request, *args, **kwargs):
        if kwargs['token']:
            try:
                token = PasswordResetToken.objects.get(token=kwargs['token'])
            except PasswordResetToken.DoesNotExist:
                kwargs['error'] = _('Your token for reseting password is invalid.')
                return render(request, self.template_form, kwargs)

            password = request.POST.get('password', '')
            password_again = request.POST.get('password_again', '')

            if len(password) < 6:
                kwargs['error'] = _('Your password is too short.')
                return render(request, self.template_form, kwargs)

            if not(password == password_again):
                kwargs['error'] = _('Your passwords mismatch.')
                return render(request, self.template_form, kwargs)

            token.user.set_password(password)
            token.user.save()
            token.delete()

            return redirect('accounts:login')
        else:
            email = request.POST.get('email', '')
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                kwargs['error'] = _('The email is invalid.')
                return render(request, self.template_email, kwargs)

            # Generate the token.
            token, created = PasswordResetToken.objects.get_or_create(user=user)
            token.token = random_hash()
            token.save()

            reset_url = reverse('accounts:password-reset') + '?token=' + token.token

            send_mail(_('Password Reset'), reset_url, 'from@example.com',
                [email], fail_silently=False)

            redirect_url = reverse('accounts:password-reset') + '?email=' + quote(email)
            return redirect(redirect_url)


class SubscriptionView(TemplateView):
    template_name = 'accounts/subscription.html'

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(self.__class__, self).dispatch(
            request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        try:
            context['subscription'] = Subscription.objects.get(
                user=self.request.user)
        except Subscription.DoesNotExist:
            context['subscription'] = None

        return context


class SubscriptionBillingView(TemplateView):
    template_name = 'accounts/subscription_billing.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(self.__class__, self).dispatch(
            request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context['plans'] = SubscriptionPlan.objects.order_by('level')

        for plan in context['plans']:
            paypal_dict = {
                'invoice': random_hash(),
                'business': settings.PAYPAL_RECEIVER_EMAIL,
                'amount': plan.price,
                'item_number': plan.id,
                'item_name': plan.name,
                'custom': b16encode(self.request.user.email),
                'notify_url': settings.SITE_URL + reverse('paypal-ipn'),
                'return_url': settings.SITE_URL + reverse('accounts:subscription'),
                'cancel_return': settings.SITE_URL + reverse('accounts:subscription-billing'),
            }
            plan.form = PayPalPaymentsForm(initial=paypal_dict)

        return context


class ProfileView(TemplateView):
    template_name = 'accounts/profile.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(self.__class__, self).dispatch(
            request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context['courses'] = Course.of_user(self.request.user)

        for course in context['courses']:
            course.date_enrolled = \
                CourseEnrollment.objects.get(
                    user=self.request.user, course=course).date_enrolled
            course.completed = \
                course.percentage_completed_of_user(self.request.user)[2]

        context['questions'] = DiscussionQuestion.objects.filter(
            user=self.request.user).order_by('-date_created')[:10]

        return context


class ProfileEditView(FormView):
    form_class = ProfileEditForm
    template_name = 'accounts/profile_edit.html'

    def get_initial(self):
        initial = super(self.__class__, self).get_initial()

        initial['first_name'] = self.request.user.first_name
        initial['last_name'] = self.request.user.last_name

        return initial

    def form_valid(self, form):
        user = self.request.user

        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']

        user.save()

litrus/modules/pages/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'pages/home.html'

litrus/templates/accounts/email_validation_send.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    
    <div class="ui page stackable grid">
        <div class="row">
            <div class="seven wide centered column">
                <h1 class="ui header">
                    {% trans 'Activate your account' %}
                    <div class="sub header">{% trans 'We will send you an email with a link so you can activate it.' %}</div>
                </h1>
                <form class="ui form" method="post" action="{% url 'accounts:password-reset' %}">
                    {% csrf_token %}
                    {% if error %}
                    <div class="ui yellow message">
                        <p>{{ error }}</p>
                    </div>
                    {% endif %}
                    <div class="field">
                        <div class="ui huge left icon input">
                            <i class="mail icon"></i>
                            <input type="text" name="email" placeholder="{% trans 'Email' %}">
                        </div>
                    </div>
                    <input class="ui submit big fluid primary button" type="submit" value="{% trans 'Send' %}" />
                </form>
            </div>
        </div>
    </div>

{% endblock %}

litrus/templates/accounts/email_validation_sent.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    
    <div class="ui page stackable grid">
        <div class="row">
            <div class="eight wide centered column">
                <h1 class="ui icon header">
                    <i class="mail icon"></i>
                    <div class="content">
                        {% trans 'Check your inbox!' %}
                        <div class="ui hidden header"></div>
                        <div class="sub header">{% trans 'We sent you an email so you can activate your account' %}: <i>{{ email }}</i></div>
                    </div>
                </h1>
            </div>
        </div>
    </div>

{% endblock %}

litrus/templates/accounts/login.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    
    <div class="ui page stackable grid">
        <div class="row">
            <div class="eight wide centered column">
                <form class="ui form" method="post" action="{% url 'accounts:login' %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}">
                    {% if error %}
                    <div class="ui yellow message">
                        <p>{{ error }}</p>
                    </div>
                    {% endif %}
                    <div class="field">
                        <div class="ui huge left icon input">
                            <i class="user icon"></i>
                            <input type="text" name="username_or_email" placeholder="{% trans 'Username or Email' %}">
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui huge left icon input">
                            <i class="key icon"></i>
                            <input type="password" name="password" placeholder="{% trans 'Password' %}">
                        </div>
                    </div>
                    <input class="ui submit big fluid primary button" type="submit" value="Login" />
                </form>
                <div class="ui basic right aligned segment">
                    <a href="{% url 'accounts:password-reset' %}">Lost your password?</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

litrus/templates/accounts/password_reset_email.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    
    <div class="ui page stackable grid">
        <div class="row">
            <div class="seven wide centered column">
                <h1 class="ui header">
                    {% trans 'Reset your password' %}
                    <div class="sub header">{% trans 'We will send you an email with a link so you can change it.' %}</div>
                </h1>
                <form class="ui form" method="post" action="{% url 'accounts:password-reset' %}">
                    {% csrf_token %}
                    {% if error %}
                    <div class="ui yellow message">
                        <p>{{ error }}</p>
                    </div>
                    {% endif %}
                    <div class="field">
                        <div class="ui huge left icon input">
                            <i class="mail icon"></i>
                            <input type="text" name="email" placeholder="{% trans 'Account Email' %}">
                        </div>
                    </div>
                    <input class="ui submit big fluid primary button" type="submit" value="{% trans 'Send' %}" />
                </form>
            </div>
        </div>
    </div>

{% endblock %}

litrus/templates/accounts/password_reset_form.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    
    <div class="ui page stackable grid">
        <div class="row">
            <div class="eight wide centered column">
                <form class="ui form" method="post" action="{% url 'accounts:password-reset' %}">
                    {% csrf_token %}
                    <input type="hidden" name="token" value="{{ token }}">
                    {% if error %}
                    <div class="ui yellow message">
                        <p>{{ error }}</p>
                    </div>
                    {% endif %}
                    <div class="field">
                        <div class="ui huge left icon input">
                            <i class="key icon"></i>
                            <input type="password" name="password" placeholder="{% trans 'New Password' %}">
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui huge left icon input">
                            <i class="key icon"></i>
                            <input type="password" name="password_again" placeholder="{% trans 'Confirm New Password' %}">
                        </div>
                    </div>
                    <input class="ui submit big fluid primary button" type="submit" value="{% trans 'Reset' %}" />
                </form>
            </div>
        </div>
    </div>

{% endblock %}

litrus/templates/accounts/profile.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
    
{% block content %}
    
    <div class="ui stackable page grid">
        <div class="four wide column">
            {% if request.user.first_name and request.user.last_name %}
            <h1 class="ui header">{{ request.user.first_name }} {{ request.user.last_name }}</h1>
            {% endif %}
            <div class="ui hidden divider"></div>
            {% block menu %}
            <div class="ui vertical fluid pointing menu">
                <a href="{% url 'accounts:profile' %}" class="{% if not active_tab %}active {% endif %}item">{% trans 'My Courses' %}</a>
                <a href="{% url 'accounts:profile-edit' %}" class="{% if active_tab == "profile" %}active {% endif %}item">{% trans 'Profile' %}</a>
                <a href="{% url 'accounts:subscription' %}" class="{% if active_tab == "subscription" %}active {% endif %}item">{% trans 'Subscription' %}</a>
                <a href="{% url 'accounts:settings' %}" class="{% if active_tab == "settings" %}active {% endif %}item">{% trans 'Settings' %}</a>
            </div>
            {% endblock %}
        </div>
        <div class="twelve wide column">
            {% block subcontent %}
            <div class="ui top attached secondary segment">
                <h3 class="ui header">{% trans 'My Courses' %}</h3>
            </div>
            <div class="ui attached segment">
                <div class="ui items">
                    {% for course in courses %}
                    <div class="item">
                        <div class="ui tiny image"><img src="{% if course.logo %}{{ course.logo.url }}{% else %}{% static 'img/no-image.gif' %}{% endif %}"></div>
                        <div class="content">
                            <a href="{{ course.get_dashboard_url }}" class="header">{{ course.name }}</a>
                            <div class="meta">
                                <span>Enrolled {{ course.date_enrolled | timesince }} ago.</span>
                            </div>
                            <div class="extra"><a class="ui tiny green label">{{ course.completed }}% {% trans 'completed' %}</a></div>
                        </div>
                    </div>
                    {% empty %}
                        <p>{% trans 'Nothing to show.' %}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="ui attached secondary segment">
                <h3 class="ui header">{% trans 'My Questions' %}</h3>
            </div>
            <div class="ui bottom attached segment">
                {% if questions %}
                <div class="ui list">
                    <div class="ui divided grid">
                    {% for question in questions %}
                        <div class="eight wide column">
                            <div class="item">
                                <div class="content">
                                    <a href="{{ question.get_absolute_url }}" class="header"><b>{{ question.title | truncatechars:20 }}</b></a>
                                    <div class="description"><span style="color:#bbb">{{ question.date_created | date:"j M, y" }}.</span> {{ question.course.name }}{% if not question.is_open %} <div class="ui mini purple label">CLOSED</div>{% endif %}</div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                </div>
                {% else %}
                <p>{% trans 'Nothing to show.' %}</p>
                {% endif %}
            </div>
            {% endblock %}
        </div>
    </div>

{% endblock %}

litrus/templates/accounts/profile_edit.html
{% extends "accounts/profile.html" %}
{% load i18n %}
{% load litrustags %}

{% block menu %}
    {% with "profile" as active_tab %} 
    {{ block.super }}
    {% endwith %}
{% endblock %}

{% block subcontent %}
    
    <div class="ui top attached secondary segment">
        <h3 class="ui header">{% trans 'Profile' %}</h3>
    </div>
    <div class="ui attached segment">
        <form class="ui error form" method="post" action="{% url 'accounts:profile-edit' %}">
            {% csrf_token %}
            {% if form.non_field_errors %}
            <div class="ui error message">
                <div class="header">{% trans 'Ups! Something is wrong' %}</div>
                <ul class="list">
                    {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
            <div class="two fields">
                <div class="field">
                    <label>Username</label>
                    <input placeholder="{{ request.user.username }}" readonly="" type="text">
                </div>
                <div class="field">
                    <label>Email</label>
                    <input placeholder="{{ request.user.email }}" readonly="" type="text">
                </div>
            </div>
            <div class="two fields">
                <div class="field{% if form.errors.first_name %} error{% endif %}">
                    <label>{{ form.first_name.label }}</label>
                    {{ form.first_name }}
                </div>
                <div class="field{% if form.errors.last_name %} error{% endif %}">
                    <label>{{ form.last_name.label }}</label>
                    {{ form.last_name }}
                </div>
            </div>
            <input class="ui submit large positive button" type="submit" value="{% trans 'Update' %}" />
        </form>
    </div>
    <div class="ui attached segment">
        <img class="ui centered rounded image" src="{% gravatar request.user.email %}&s=200">
    </div>
    <div class="ui bottom attached info message">
        <p>{% trans 'Change your image at Gravatar.' %} <a href="https://gravatar.com" target="_BLANK"><b>{% trans 'Click here!' %}</b></a></p>
    </div>
{% endblock %}

litrus/templates/accounts/register.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    
    <div class="ui page stackable grid">
        <div class="row">
            <div class="ten wide centered column">
                <form class="ui error form segment" method="post" action="{% url 'accounts:register' %}">
                    <h1 class="ui center aligned header">{% trans 'Create your account' %}</h1>
                    <div class="ui section divider"></div>
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                    <div class="ui error message">
                        <div class="header">{% trans 'Ups! Something is wrong' %}</div>
                        <ul class="list">
                            {% for error in form.non_field_errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    <div class="two fields">
                        <div class="field{% if form.errors.username %} error{% endif %}">
                            <label>{{ form.username.label }}</label>
                            {{ form.username }}
                        </div>
                        <div class="field{% if form.errors.email %} error{% endif %}">
                            <label>{{ form.email.label }}</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="two fields">
                        <div class="field{% if form.errors.password %} error{% endif %}">
                            <label>{{ form.password.label }}</label>
                            {{ form.password }}
                        </div>
                        <div class="field{% if form.errors.password_again %} error{% endif %}">
                            <label>{{ form.password_again.label }}</label>
                            {{ form.password_again }}
                        </div>
                    </div>
                    <input class="ui submit big positive button" type="submit" value="{% trans 'Register' %}" />
                </form>
            </div>
        </div>
    </div>

{% endblock %}

litrus/templates/accounts/settings.html
{% extends "accounts/profile.html" %}
{% load i18n %}

{% block menu %}
    {% with "settings" as active_tab %} 
    {{ block.super }}
    {% endwith %}
{% endblock %}

{% block subcontent %}
    
    <div class="ui top attached secondary segment">
        <h3 class="ui header">{% trans 'Settings' %}</h3>
    </div>
    <div class="ui attached segment">
        <p>{% trans 'Want to change your password?' %} <a href="{% url 'accounts:password-reset' %}" class="ui blue tiny button">{% trans 'Reset Password' %}</a></p>
    </div>

{% endblock %}